name: Run main

on:
  schedule:
    - cron: "30 3 * * *"  # Runs daily at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      HYPERBOLIC_API_KEY: ${{ secrets.HYPERBOLIC_API_KEY }}
      WP_URL: ${{ secrets.WP_URL }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Ensure Required Directories Exist
        run: |
          mkdir -p images
          chmod -R 777 images  # Grant full access to avoid permission issues

      - name: Run Main Script
        run: python main.py
